### ISSUE TITLE
StatProfiler is segfaulting under Perl 5.24

### ISSUE THREAD

**Issue by manzur** [mbarbon/devel-statprofiler#12]
Hey,

Looks like due to changes introduced in Perl 5.24, StatProfiler is segfaulting on the following line([link](https://github.com/mbarbon/devel-statprofiler/blob/master/src/tracefile.cpp#L1233)):

`GV * const cvgv = sub_name ? sub_name : CvGV(sub);`

Segfault is caused by `sub` argument having 0x0 as a value, while the block(blku_type) still has type `sub`:
```
 cx_blk = {
      blku_type = 41 ')',// 41 & 0xf => 9 (sub type) 
      blku_gimme = 1 '\001', 
.....
      blk_u = {
        blku_sub = {
          retop = 0x7f920a1b3eb8, 
          prevcomppad = 0x7f920a193c30, 
          cv = 0x0, 
          olddepth = 0, 
          savearray = 0x0
        }, 
.....
```
The breakage is caused by this commit [4df352a](https://github.com/Perl/perl5/commit/4df352a), which changed the order of calls from `cx_popblock -> cx_popsub` to `cx_popsub -> cx_popblock`.

**Comment by mbarbon** [comment]
I have not tried to reproduce this yet; before I try that, do you have a self-contained example that segfaults?
