### ISSUE TITLE
Segfault when output directory is not writable

### ISSUE THREAD

**Issue by mbarbon** [mbarbon/devel-statprofiler#9]

**Comment by Hugmeir** [comment]
Just ran into this today -- one-liner to reproduce:

`perl
sudo perl -E 'require Devel::StatProfiler; my $d = "./statprofile"; rmdir $d; mkdir $d; Devel::StatProfiler->import(qw!-template!, $dir . "/some_file"); Devel::StatProfiler::enable_profile(); ($>, $<) = (99, 99); qx(echo 1)'`

**Comment by mbarbon** [comment]
Should be fixed by 7900468159c4c70705b8e383c1b0adcba6dc86e3
